### ISSUE TITLE
No documented way to get config out of third party integration

### ISSUE THREAD

**Issue by Ulrar** [mongodb/terraform-provider-mongodbatlas#939]
### Terraform Configuration File 

```hcl
resource "mongodbatlas_third_party_integration" "test_prometheus" {
    project_id = "<PROJECT-ID>"
    type = "PROMETHEUS"
    user_name = "..."
    password = "..."
    service_discovery = "http"
    scheme = "https"
    enabled = true
}
```

### Additional Context

Hi,
I'm just looking at using the Prometheus third party integration, the [official doc](https://www.mongodb.com/docs/atlas/tutorial/prometheus-integration/) says the official web UI will output a generated snippet if done though it, which you then copy to your Prometheus config.
Looking at the [terraform provider's doc](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/third_party_integration), I don't see any way of getting that snippet back from the API, or if there is it doesn't seem documented.

I don't know if that's a "bug" per se, it looks to me like this provider can be used to enable the integration but there's no way to actually make use of it afterward. Appologies if I missed an output attribute or data type documented somewhere else.

**Comment by martinstibbe** [comment]
@Ulrar In this example you end up with this sequence of events to configure (I can update Example to show these steps) 

- Terraform apply to set up integration
- Go to Web UI click on Prometheus / View which will bring up snippet to use for prometheus.yml

```
global:
  scrape_interval: 15s
scrape_configs:

- job_name: "test-mongo-metrics"
  scrape_interval: 10s  
  metrics_path: /metrics
  scheme : https
  basic_auth:
    username: prom_user_<grp_id>
    password: <pwd>
  http_sd_configs:
    - url: https://cloud.mongodb.com/prometheus/v1.0/groups/<grp_id>discovery
      refresh_interval: 60s
      basic_auth:
        username: prom_user_<grp_id>
        password: <pwd>
```

- Then run the prometheus container using this supplied configuration yml file
